sentry:
  dsn: '%env(SENTRY_DSN)%'
  options:
    curl_method: async
    environment: '%env(LINIO_ENV)%'

  skip_capture:
    - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
    - 'Symfony\Component\HttpKernel\Exception\BadRequestHttpException'
    - 'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException'
    - 'Symfony\Component\HttpKernel\Exception\HttpExceptionInterface'
