version: '3.7'
services:
  php-cs-fixer:
    image: 137361304112.dkr.ecr.us-east-1.amazonaws.com/seller-signup-form-php:latest
    init: true
    volumes:
      - .:/application
    entrypoint: vendor/bin/php-cs-fixer
    command: fix --verbose --show-progress=estimating

  composer:
    image: 137361304112.dkr.ecr.us-east-1.amazonaws.com/seller-signup-form-php:latest
    init: true
    volumes:
      - .:/application
      - composer-cache:/root/.composer/cache
      - ${COMPOSER_HOME:-~/.composer}/auth.json:/root/.composer/auth.json
    entrypoint: composer

  php:
    image: 137361304112.dkr.ecr.us-east-1.amazonaws.com/seller-signup-form-php:latest
    init: true
    volumes:
      - .:/application

  node:
    image: 137361304112.dkr.ecr.us-east-1.amazonaws.com/docker-node:0.1
    init: true
    volumes:
      - .:/application
      - yarn-cache:/root/.cache/yarn/v1
    command: sh

  yarn:
    image: 137361304112.dkr.ecr.us-east-1.amazonaws.com/docker-node:0.1
    init: true
    volumes:
      - .:/application
      - yarn-cache:/root/.cache/yarn/v1
    entrypoint: yarn

volumes:
  composer-cache: ~
  yarn-cache: ~
