monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
      excluded_404s:
        # regex: exclude all 404 errors from the logs
        - ^/
    nested:
      type: stream
      path: '%env(resolve:LOG_PATH)%.log'
      level: debug
      formatter: Linio\Log\LinioStandardsFormatter
    console:
      type: console
      process_psr_3_messages: false
      channels: ['!event', '!doctrine']
    deprecation:
      type: stream
      path: '%env(resolve:LOG_PATH)%.deprecations.log'
    deprecation_filter:
      type: filter
      handler: deprecation
      max_level: info
      channels: ['php']
