healthCheck:
  path: /_healthcheck
  controller: App\Controller\ContactController::healthCheckAction

index:
  path: /{store}
  controller: App\Controller\ContactController::index
  defaults:
    store: mx
